name: Flutter Build and Upload Android APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest # Ubuntu is sufficient for Android builds

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2

      - name: Install dependencies
        run: flutter pub get

      - name: Build Android APK
        run: flutter build apk --release

      # Upload the APK as an artifact
      - name: Upload Android APK
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: build/app/outputs/flutter-apk/app-release.apk