name: Flutter Build and Upload Android APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2

      # Navigate to the Flutter project directory
      # If your Flutter project is in a subdirectory, update this value
      - name: Install dependencies
        run: flutter pub get
        working-directory: better_bee_app-main

      - name: Build Android APK
        run: flutter build apk --release
        working-directory: better_bee_app-main

      - name: Upload Android APK
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: better_bee_app-main/build/app/outputs/flutter-apk/app-release.apk
